# Generated by Django 3.0.3 on 2020-08-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('roomcode', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Classroom',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('subject', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, null=True)),
                ('times', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Exam',
            },
        ),
        migrations.CreateModel(
            name='Exampupil',
            fields=[
                ('examcode', models.TextField(blank=True, null=True)),
                ('pupilid', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ExamPupil',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('birthdate', models.TextField(blank=True, null=True)),
                ('accessarrangement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
