# Generated by Django 3.0.3 on 2020-08-14 14:05

from django.db import migrations

def link_exams(apps, schema_editor):
    Exampupil = apps.get_model('database', 'Exampupil')
    Exam = apps.get_model('database', 'Exam')
    Student = apps.get_model('database', 'Student')
    for b in Exampupil.objects.all():
        b.examcode_link = Exam.objects.filter(code=b.examcode).first()
        b.save()
        b.studentid_link = Student.objects.filter(studentid=b.pupilid).first()
        b.save()

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200814_2152'),
    ]

    operations = [
            migrations.RunPython(link_exams)
    ]
