# Generated by Django 3.0.3 on 2020-08-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_transfer_fields'),
    ]

    operations = [
        migrations.RemoveField('Exampupil','examcode'),
        migrations.RemoveField('Exampupil','pupilid'),
    ]
