# Generated by Django 3.0.3 on 2020-08-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampupil',
            name='examcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exampupil',
            name='pupilid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
