# Generated by Django 3.0.3 on 2020-08-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200815_2304'),
    ]

    operations = [
    ]
