# Generated by Django 3.0.3 on 2020-08-16 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_populate_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('examcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Exam')),
                ('roomcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Classroom')),
            ],
        ),
    ]
