# Generated by Django 3.0.3 on 2020-08-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_examroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamRoom',
        ),
    ]
