# Generated by Django 3.0.3 on 2020-08-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200819_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampupil',
            name='examcode_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Exam'),
        ),
        migrations.AlterField(
            model_name='exampupil',
            name='studentid_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Student'),
        ),
    ]
